Entities/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChanceQuest.Entities
{
    public class Player
    {
        public int Id { get; set; }
        public string CharacterName { get; set; }
        public int PeasantHappiness { get; set; }
        public int NobleHappiness { get; set; }
        public int RoyalHappiness { get; set; }
        public int FavorableStatId { get; set; } //1 = str, 2 = int, 3 = dex

        public bool IsDeleted { get; set; } // Check whether a player has been deleted
    }
}

Models/Player/CreatePlayerCommand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChanceQuest.Entities;
using ChanceQuest.Models.Player;

namespace ChanceQuest.Models
{
    public class CreatePlayerCommand : EditPlayer
    {
        public ChanceQuest.Entities.Player ToPlayer()
        {
            return new ChanceQuest.Entities.Player
            {
                CharacterName = CharacterName,
                PeasantHappiness = PeasantHappiness,
                NobleHappiness = NobleHappiness,
                RoyalHappiness = RoyalHappiness,
                FavorableStatId = FavorableStatId
            };
        }
    }
}

Models/Player/EditPlayer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChanceQuest.Models.Player
{
    public class EditPlayer
    {
        public int Id { get; set; }
        public string CharacterName { get; set; }
        public int PeasantHappiness { get; set; }
        public int NobleHappiness { get; set; }
        public int RoyalHappiness { get; set; }
        public int FavorableStatId { get; set; } //1 = str, 2 = int, 3 = dex
    }
}

Models/Player/NobleHappinessUpdateCommand.cs
namespace ChanceQuest
{
    public class NobleHappinessUpdateCommand
    {
        public int NobleHappiness { get; internal set; }
    }
}

Models/Player/NobleHappyPlus.cs
namespace ChanceQuest
{
    public class NobleHappyPlus
    {
        public int NobleHappiness { get; internal set; }
    }
}

Models/Player/PeasantHappinessUpdateCommand.cs
namespace ChanceQuest
{
    internal class PeasantHappinessUpdateCommand
    {
        public int PeasantHappiness { get; internal set; }
    }
}

Models/Player/PeasantHappyPlus.cs
namespace ChanceQuest
{
    public class PeasantHappyPlus
    {
        public int PeasantHappiness { get; internal set; }
    }
}

Models/Player/PlayerDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChanceQuest.Models.Player
{
    public class PlayerDetails
    {
        public int Id { get; set; }

        public string CharacterName { get; set; }
        public int PeasantHappiness { get; set; }
        public int NobleHappiness { get; set; }
        public int RoyalHappiness { get; set; }
        public int FavorableStatId { get; set; }
        public DateTime LastModified { get; internal set; }
    }
}

Models/Player/PlayerStateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChanceQuest.Models.Player
{
    public class PlayerStateViewModel
    {
        public int Id { get; internal set; }
        public int PeasantHappiness { get; internal set; }
        public int NobleHappiness { get; internal set; }
        public int RoyalHappiness { get; internal set; }
    }
}

Models/Player/PlayerSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChanceQuest.Models.Player
{
    public class PlayerSummary
    {
        public int Id { get; set; }
        public string CharacterName { get; set; }
        public int PeasantHappiness { get; set; }
        public int NobleHappiness { get; set; }
        public int RoyalHappiness { get; set; }
        public int FavorableStatId { get; set; }

        public static PlayerSummary FromPlayer(PlayerSummary ps)
        {
            return new PlayerSummary
            {
                Id = ps.Id,
                CharacterName = ps.CharacterName,
                PeasantHappiness = ps.PeasantHappiness,
                NobleHappiness = ps.NobleHappiness,
                RoyalHappiness = ps.RoyalHappiness,
            };
        }
    }
}

Models/Player/RoyalHappinessUpdateCommand.cs
namespace ChanceQuest
{
    public class RoyalHappinessUpdateCommand
    {
        public int RoyalHappiness { get; internal set; }
    }
}

Models/Player/RoyalHappyMinus.cs
namespace ChanceQuest
{
    public class RoyalHappyMinus
    {
        public int RoyalHappiness { get; internal set; }
    }
}

Models/Player/UpdatePlayerCommand.cs
using ChanceQuest.Data;
using ChanceQuest.Models.Player;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace ChanceQuest.Models.Player
{
    public class UpdatePlayerCommand : EditPlayer
    {
        public int Id { get; set; }

        public void UpdatePlayer(ChanceQuest.Entities.Player player)
        {
            player.CharacterName = CharacterName;
            player.PeasantHappiness = PeasantHappiness;
            player.RoyalHappiness = RoyalHappiness;
            player.FavorableStatId = FavorableStatId;
        }
    }
}

Controllers/PlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ChanceQuest.Data;
using ChanceQuest.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ChanceQuest.Controllers
{
    public class PlayController : Controller
    {
        private readonly GameService _service;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _playerService;
        private readonly IAuthorizationService _authService;
        private readonly ILogger<PlayController> _logger;


        public PlayController(
            GameService service,
            UserManager<IdentityUser> playerService, ApplicationDbContext context,
            IAuthorizationService authService, ILogger<PlayController> logger)
        {
            _service = service;
            _playerService = playerService;
            _context = context;
            _authService = authService;
            _logger = logger;
        }
        public IActionResult Index(GameViewModel model) 
        {
            UpdatePlayer(model); // gets the user id and calls update method

            Random rand = new Random(); //gets 3 ints between 1 - 15 to choose quest Id
            int result1 = rand.Next(1, 15);
            int result2 = rand.Next(1, 15);
            int result3 = rand.Next(1, 15);

            var quest1 = _service.GetNewQuest(result1); //gets new quests
            var quest2 = _service.GetNewQuest(result2);
            var quest3 = _service.GetNewQuest(result3);

            return View(model);
        }
        public void UpdatePlayer(GameViewModel model)
        {
            if (model == null)
            {
                _logger.LogWarning("Error");
                throw new Exception("Unable to find player");
            }

            Random rand = new Random();
            int result = rand.Next(1, 100);
            int faction = rand.Next(1, 3);
            int pos, neg; bool success = false;

            if (result < 50)
            {
                pos = 0; //when player loses a quest - 50/50 chance
                neg = -5;
            }
            else //if result is 50+
            {
                pos = 20; //faction gets +20 happiness when quest succeeds
                neg = -5;
                success = true;
            }

            if (success == true)
            {
                if (faction == 1)
                {
                    _service.PeasantHappinessUpdate(model.Id, pos);
                    _service.NobleHappinessUpdate(model.Id, neg);
                    _service.RoyalHappinessUpdate(model.Id, neg);

                }
                else if (faction == 2)
                {
                    _service.PeasantHappinessUpdate(model.Id, neg);
                    _service.NobleHappinessUpdate(model.Id, pos);
                    _service.RoyalHappinessUpdate(model.Id, neg);
                }
                else if (faction == 3)
                {
                    _service.PeasantHappinessUpdate(model.Id, neg);
                    _service.NobleHappinessUpdate(model.Id, neg);
                    _service.RoyalHappinessUpdate(model.Id, pos);
                }
            }
            else
            {
                _service.PeasantHappinessUpdate(model.Id, neg);
                _service.NobleHappinessUpdate(model.Id, neg);
                _service.RoyalHappinessUpdate(model.Id, neg);
            }
        }
    }
}

Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChanceQuest.Data;
using ChanceQuest.Entities;

namespace ChanceQuest.Controllers
{
    public class PlayerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Player
        public async Task<IActionResult> Index()
        {
            return View(await _context.Player.ToListAsync());
        }

        // GET: Player/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Player/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CharacterName,PeasantHappiness,NobleHappiness,RoyalHappiness,FavorableStatId,IsDeleted")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Player/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Player/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CharacterName,PeasantHappiness,NobleHappiness,RoyalHappiness,FavorableStatId,IsDeleted")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Player/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Player.FindAsync(id);
            _context.Player.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Player.Any(e => e.Id == id);
        }
    }
}

Views/Player/Create.cshtml
@model ChanceQuest.Entities.Player

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CharacterName" class="control-label"></label>
                <input asp-for="CharacterName" class="form-control" />
                <span asp-validation-for="CharacterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PeasantHappiness" class="control-label"></label>
                <input asp-for="PeasantHappiness" class="form-control" />
                <span asp-validation-for="PeasantHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NobleHappiness" class="control-label"></label>
                <input asp-for="NobleHappiness" class="form-control" />
                <span asp-validation-for="NobleHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoyalHappiness" class="control-label"></label>
                <input asp-for="RoyalHappiness" class="form-control" />
                <span asp-validation-for="RoyalHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FavorableStatId" class="control-label"></label>
                <input asp-for="FavorableStatId" class="form-control" />
                <span asp-validation-for="FavorableStatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Player/Delete.cshtml
@model ChanceQuest.Entities.Player

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PeasantHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeasantHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NobleHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NobleHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoyalHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoyalHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FavorableStatId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FavorableStatId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Player/Details.cshtml
@model ChanceQuest.Entities.Player

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PeasantHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeasantHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NobleHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NobleHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoyalHappiness)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoyalHappiness)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FavorableStatId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FavorableStatId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" asp-controller="Play">Play Game</a>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Player/Edit.cshtml
@model ChanceQuest.Entities.Player

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CharacterName" class="control-label"></label>
                <input asp-for="CharacterName" class="form-control" />
                <span asp-validation-for="CharacterName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PeasantHappiness" class="control-label"></label>
                <input asp-for="PeasantHappiness" class="form-control" />
                <span asp-validation-for="PeasantHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NobleHappiness" class="control-label"></label>
                <input asp-for="NobleHappiness" class="form-control" />
                <span asp-validation-for="NobleHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoyalHappiness" class="control-label"></label>
                <input asp-for="RoyalHappiness" class="form-control" />
                <span asp-validation-for="RoyalHappiness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FavorableStatId" class="control-label"></label>
                <input asp-for="FavorableStatId" class="form-control" />
                <span asp-validation-for="FavorableStatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Player/Index.cshtml
@model IEnumerable<ChanceQuest.Entities.Player>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CharacterName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PeasantHappiness)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NobleHappiness)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoyalHappiness)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FavorableStatId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CharacterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PeasantHappiness)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NobleHappiness)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoyalHappiness)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FavorableStatId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>